#!/usr/bin/env python3
"""LAW_OF_SKILLS v2 — metrics rollup.

Reads ``BRAIN/06_Operations/Skill_Ledger.md`` History blocks, computes
per-session invocation counts, and writes a rolling snapshot to
``BRAIN/06_Operations/Skill_Metrics.md``.

Tracks:
  - skill invocations per session (count, role distribution)
  - missed-trigger sessions (sessions whose ledger lacks rows for a
    required tool; sourced from the matching session log)
  - audit-pass rate
  - top skills by usage

Run after rotating Active → History, or weekly.

Usage:
  python scripts/doctrine/metrics.py update
"""
from __future__ import annotations

import os
import re
import sys
import tempfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LEDGER = REPO_ROOT / "BRAIN" / "06_Operations" / "Skill_Ledger.md"
METRICS = REPO_ROOT / "BRAIN" / "06_Operations" / "Skill_Metrics.md"
_CREATED_RE = re.compile(r"^created:\s*(\d{4}-\d{2}-\d{2})", re.M)


def _preserved_created_date() -> str:
    """Read the existing `created:` value from Skill_Metrics.md so
    successive `update` runs don't overwrite it with today's date."""
    if METRICS.exists():
        m = _CREATED_RE.search(METRICS.read_text(encoding="utf-8"))
        if m:
            return m.group(1)
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _atomic_write(path: Path, content: str) -> None:
    """Write via temp + rename so an interrupted run never corrupts."""
    if path.exists() and path.is_symlink():
        raise SystemExit(f"SECURITY: {path} is a symlink — refusing to write")
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmpname = tempfile.mkstemp(
        prefix=path.name + ".", suffix=".tmp", dir=str(path.parent)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
        os.replace(tmpname, str(path))
    except Exception:
        try:
            os.unlink(tmpname)
        except OSError:
            pass
        raise


def parse_history() -> dict[str, list[dict[str, str]]]:
    """Return {session-slug: [{timestamp, skill, role, task_id, status, evidence}]}."""
    if not LEDGER.exists():
        return {}
    text = LEDGER.read_text(encoding="utf-8")
    after_history = re.split(r"\n##\s*History\b", text, maxsplit=1)
    if len(after_history) != 2:
        return {}
    history = after_history[1]
    sessions: dict[str, list[dict[str, str]]] = {}
    # Each session header looks like:  ### YYYY-MM-DD — slug
    pattern = re.compile(
        r"###\s*\d{4}-\d{2}-\d{2}\s+[—-]+\s+(?P<slug>[^\n]+)\n+\|.*?\n\|---.*?\n((?:\|.*\n)*)",
        re.S,
    )
    for m in pattern.finditer(history):
        slug = m.group("slug").strip()
        rows: list[dict[str, str]] = []
        for line in m.group(2).splitlines():
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 7:
                continue
            ts, session, skill, role, task_id, status, evidence = cells[:7]
            rows.append(
                {
                    "timestamp": ts,
                    "skill": skill,
                    "role": role,
                    "task_id": task_id,
                    "status": status,
                    "evidence": evidence,
                }
            )
        sessions.setdefault(slug, []).extend(rows)
    return sessions


def render(sessions: dict[str, list[dict[str, str]]]) -> str:
    total_invocations = sum(len(rows) for rows in sessions.values())
    total_sessions = len(sessions)
    skill_counts: Counter[str] = Counter()
    role_counts: Counter[str] = Counter()
    status_counts: Counter[str] = Counter()
    for rows in sessions.values():
        for r in rows:
            skill_counts[r["skill"]] += 1
            role_counts[r["role"]] += 1
            short_status = r["status"].split(":", 1)[0].strip().lower()
            status_counts[short_status] += 1

    waived = status_counts.get("waived", 0)
    errored = status_counts.get("error", 0)
    pass_rate = (
        ((total_invocations - errored - waived) / total_invocations) * 100
        if total_invocations
        else 0.0
    )

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append("---")
    lines.append(f"created: {_preserved_created_date()}")
    lines.append(f"updated: {now}")
    lines.append("tags: [operations, metrics, skills, derived]")
    lines.append("note: GENERATED by scripts/doctrine/metrics.py — do not edit by hand")
    lines.append("---")
    lines.append("")
    lines.append("# Skill Metrics — derived from Skill_Ledger")
    lines.append("")
    lines.append(f"> Auto-generated {now}. Re-run `python scripts/doctrine/metrics.py update` after every session-end rotate.")
    lines.append("")
    lines.append("## Rolling totals")
    lines.append("")
    lines.append(f"- Sessions tracked: **{total_sessions}**")
    lines.append(f"- Total invocations: **{total_invocations}**")
    lines.append(f"- Effective pass rate (excludes errors + waivers): **{pass_rate:.1f}%**")
    lines.append(f"- Errors: {errored} · Waivers: {waived}")
    lines.append("")
    lines.append("## Top skills (by invocation count)")
    lines.append("")
    lines.append("| Skill | Calls |")
    lines.append("|---|---|")
    for skill, n in skill_counts.most_common(15):
        lines.append(f"| `{skill}` | {n} |")
    lines.append("")
    lines.append("## Role distribution")
    lines.append("")
    lines.append("| Role | Calls |")
    lines.append("|---|---|")
    for role, n in role_counts.most_common():
        lines.append(f"| {role} | {n} |")
    lines.append("")
    lines.append("## Per-session detail")
    lines.append("")
    lines.append("| Session | Invocations | Skills used |")
    lines.append("|---|---|---|")
    for slug, rows in sorted(sessions.items()):
        skills = sorted({r["skill"] for r in rows})
        lines.append(f"| {slug} | {len(rows)} | {', '.join(f'`{s}`' for s in skills)} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Trend analysis")
    lines.append("")
    lines.append(
        "If 'Top skills' shows `python-reviewer` < `code-reviewer` × 0.3 over the last "
        "10 sessions, the backend likely isn't being reviewed proportionally to its share "
        "of changed files. Investigate."
    )
    lines.append("")
    lines.append(
        "If 'Effective pass rate' < 90%, audit-blocking errors are creeping in. Open the most "
        "recent `04_Sessions/` log and walk back the failed invocations."
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) < 2 or sys.argv[1] != "update":
        print("usage: metrics.py update", file=sys.stderr)
        return 2
    sessions = parse_history()
    _atomic_write(METRICS, render(sessions))
    print(f"wrote {METRICS} ({len(sessions)} session(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
