"""hitl tables and call columns

Revision ID: 243544911129
Revises: 9b04b2ff3b4c
Create Date: 2026-04-17 22:11:45.817852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '243544911129'
down_revision: Union[str, None] = '9b04b2ff3b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('failing_checkpoints', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_decisions_call_id'), 'compliance_decisions', ['call_id'], unique=False)
    op.create_index(op.f('ix_compliance_decisions_created_at'), 'compliance_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_decisions_is_current'), 'compliance_decisions', ['is_current'], unique=False)
    op.create_table('review_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('release_reason', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_sessions_call_id'), 'review_sessions', ['call_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_is_active'), 'review_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_review_sessions_last_activity_at'), 'review_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_review_sessions_reviewer_id'), 'review_sessions', ['reviewer_id'], unique=False)
    op.create_table('claim_locks',
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('review_session_id', sa.String(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_claim_locks_expires_at'), 'claim_locks', ['expires_at'], unique=False)
    op.create_table('transcript_edits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('word_index', sa.Integer(), nullable=False),
    sa.Column('word_start_ms', sa.Integer(), nullable=False),
    sa.Column('old_text', sa.String(), nullable=False),
    sa.Column('new_text', sa.String(), nullable=False),
    sa.Column('edited_by', sa.String(), nullable=False),
    sa.Column('review_session_id', sa.String(), nullable=True),
    sa.Column('triggered_checkpoint_id', sa.String(), nullable=True),
    sa.Column('triggered_reanalysis', sa.Boolean(), nullable=False),
    sa.Column('reanalysis_changed_verdict', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_edits_call_id'), 'transcript_edits', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcript_edits_created_at'), 'transcript_edits', ['created_at'], unique=False)
    op.create_table('verdict_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('checkpoint_id', sa.String(), nullable=False),
    sa.Column('review_session_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdict_history_call_id'), 'verdict_history', ['call_id'], unique=False)
    op.create_index(op.f('ix_verdict_history_checkpoint_id'), 'verdict_history', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_verdict_history_created_at'), 'verdict_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_verdict_history_is_current'), 'verdict_history', ['is_current'], unique=False)
    op.add_column('calls', sa.Column('review_status', sa.String(), nullable=False))
    op.add_column('calls', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('calls', sa.Column('reviewed_by', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('compliance_status', sa.String(), nullable=False))
    op.add_column('calls', sa.Column('compliance_source', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('compliance_decided_at', sa.DateTime(), nullable=True))
    op.add_column('calls', sa.Column('compliance_decided_by', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('compliance_comment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_calls_compliance_status'), 'calls', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_calls_review_status'), 'calls', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_review_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_compliance_status'), table_name='calls')
    op.drop_column('calls', 'compliance_comment')
    op.drop_column('calls', 'compliance_decided_by')
    op.drop_column('calls', 'compliance_decided_at')
    op.drop_column('calls', 'compliance_source')
    op.drop_column('calls', 'compliance_status')
    op.drop_column('calls', 'reviewed_by')
    op.drop_column('calls', 'reviewed_at')
    op.drop_column('calls', 'review_status')
    op.drop_index(op.f('ix_verdict_history_is_current'), table_name='verdict_history')
    op.drop_index(op.f('ix_verdict_history_created_at'), table_name='verdict_history')
    op.drop_index(op.f('ix_verdict_history_checkpoint_id'), table_name='verdict_history')
    op.drop_index(op.f('ix_verdict_history_call_id'), table_name='verdict_history')
    op.drop_table('verdict_history')
    op.drop_index(op.f('ix_transcript_edits_created_at'), table_name='transcript_edits')
    op.drop_index(op.f('ix_transcript_edits_call_id'), table_name='transcript_edits')
    op.drop_table('transcript_edits')
    op.drop_index(op.f('ix_claim_locks_expires_at'), table_name='claim_locks')
    op.drop_table('claim_locks')
    op.drop_index(op.f('ix_review_sessions_reviewer_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_last_activity_at'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_is_active'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_call_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_index(op.f('ix_compliance_decisions_is_current'), table_name='compliance_decisions')
    op.drop_index(op.f('ix_compliance_decisions_created_at'), table_name='compliance_decisions')
    op.drop_index(op.f('ix_compliance_decisions_call_id'), table_name='compliance_decisions')
    op.drop_table('compliance_decisions')
    # ### end Alembic commands ###
