"""add audio_storage_key to calls

Revision ID: 769639f5e6a0
Revises: 8824b5f46018
Create Date: 2026-04-17 22:23:37.128559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769639f5e6a0'
down_revision: Union[str, None] = '8824b5f46018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('audio_storage_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_calls_audio_storage_key'), 'calls', ['audio_storage_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_audio_storage_key'), table_name='calls')
    op.drop_column('calls', 'audio_storage_key')
    # ### end Alembic commands ###
