"""initial schema

Revision ID: 9b04b2ff3b4c
Revises: 
Create Date: 2026-04-17 22:03:17.330725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b04b2ff3b4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_learnings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('checkpoint_name', sa.String(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('agent_verdict', sa.String(), nullable=False),
    sa.Column('human_verdict', sa.String(), nullable=False),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_learnings_checkpoint_name'), 'agent_learnings', ['checkpoint_name'], unique=False)
    op.create_index(op.f('ix_agent_learnings_supplier'), 'agent_learnings', ['supplier'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('script_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('checkpoints', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('script_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('checkpoints_snapshot', sa.Text(), nullable=False),
    sa.Column('mode_snapshot', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('gemini_transcript', sa.Text(), nullable=True),
    sa.Column('assemblyai_transcript', sa.Text(), nullable=True),
    sa.Column('groq_whisper_transcript', sa.Text(), nullable=True),
    sa.Column('cohere_transcript', sa.Text(), nullable=True),
    sa.Column('word_data', sa.Text(), nullable=True),
    sa.Column('compliant', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('script_id', sa.String(), nullable=True),
    sa.Column('script_version_id', sa.String(), nullable=True),
    sa.Column('checkpoint_results', sa.Text(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('detected_supplier', sa.String(), nullable=True),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_checkpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('call_id', sa.String(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('reviewer_verdict', sa.String(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_checkpoints')
    op.drop_table('calls')
    op.drop_table('script_versions')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_agent_learnings_supplier'), table_name='agent_learnings')
    op.drop_index(op.f('ix_agent_learnings_checkpoint_name'), table_name='agent_learnings')
    op.drop_table('agent_learnings')
    # ### end Alembic commands ###
