"""add draft fields to calls

Revision ID: a61574d004a0
Revises: a1b3c5e7f9d0
Create Date: 2026-04-18 01:10:27.850724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61574d004a0'
down_revision: Union[str, None] = 'a1b3c5e7f9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('draft_snapshot', sa.Text(), nullable=True))
    op.add_column('calls', sa.Column('draft_saved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'draft_saved_at')
    op.drop_column('calls', 'draft_snapshot')
    # ### end Alembic commands ###
