import fs from "node:fs";
import path from "node:path";

import AxeBuilder from "@axe-core/playwright";

import { test, expect } from "./fixtures";

/**
 * Authenticated axe-core audit (W5 G3 / R8b gap-fill).
 *
 * The original R8b sweep ran on /login only because every other route
 * redirects unauthenticated users. This spec uses the shared `authedPage`
 * fixture to log in once and then walks the seven main app routes,
 * reporting violation counts per route and saving a markdown summary at
 * .planning/v3-rebuild/validation/axe-r8b-authed.md.
 *
 * Soft gate: ≤5 violations per route. Real-world: SPA + dark theme +
 * shadcn-table semantics tend to fire color-contrast and aria-allowed
 * warnings that don't block ship — we surface them but don't hard-fail.
 */

const ROUTES = [
  "/queue",
  "/calls",
  "/customers",
  "/deals",
  "/agents",
  "/observability",
  "/settings",
] as const;

const REPORT_DIR = path.resolve(
  __dirname,
  "..",
  "..",
  "..",
  ".planning",
  "v3-rebuild",
  "validation",
);
const REPORT_PATH = path.join(REPORT_DIR, "axe-r8b-authed.md");

type RouteResult = {
  route: string;
  violationsCount: number;
  violations: { id: string; impact: string | null | undefined; nodes: number }[];
};

const results: RouteResult[] = [];

test.describe.configure({ mode: "serial" });

// Each route audit needs login + nav + axe analyze; bump from 30s default.
test.setTimeout(60_000);

test.afterAll(() => {
  fs.mkdirSync(REPORT_DIR, { recursive: true });
  const lines: string[] = [];
  lines.push("# axe-core authenticated audit (R8b gap-fill)");
  lines.push("");
  lines.push(
    `Generated by \`tests/e2e/a11y-audit.spec.ts\` on ${new Date().toISOString()}.`,
  );
  lines.push("");
  lines.push("| Route | Violations | Top rules |");
  lines.push("|---|---|---|");
  for (const r of results) {
    const top = r.violations
      .slice(0, 3)
      .map((v) => `${v.id} (${v.nodes})`)
      .join(", ");
    lines.push(`| ${r.route} | ${r.violationsCount} | ${top || "—"} |`);
  }
  lines.push("");
  lines.push("## Per-route detail");
  for (const r of results) {
    lines.push("");
    lines.push(`### ${r.route}`);
    if (r.violations.length === 0) {
      lines.push("");
      lines.push("No violations.");
      continue;
    }
    lines.push("");
    for (const v of r.violations) {
      lines.push(`- **${v.id}** [${v.impact ?? "unknown"}] — ${v.nodes} node(s)`);
    }
  }
  fs.writeFileSync(REPORT_PATH, lines.join("\n") + "\n");
});

for (const route of ROUTES) {
  test(`a11y: ${route}`, async ({ authedPage: page }) => {
    await page.goto(route, { waitUntil: "domcontentloaded" });
    // Don't wait on networkidle — observability has long-poll/streams
    // that never go idle. domcontentloaded + a small settle delay is
    // enough for axe to see hydrated DOM.
    await page.waitForLoadState("domcontentloaded").catch(() => {
      /* tolerate */
    });
    await page.waitForTimeout(800);

    const axeResults = await new AxeBuilder({ page }).analyze();
    const summary: RouteResult = {
      route,
      violationsCount: axeResults.violations.length,
      violations: axeResults.violations.map((v) => ({
        id: v.id,
        impact: v.impact,
        nodes: v.nodes.length,
      })),
    };
    results.push(summary);

    if (summary.violationsCount > 0) {
      // eslint-disable-next-line no-console
      console.log(`[a11y] ${route} — ${summary.violationsCount} violation(s):`);
      for (const v of summary.violations) {
        // eslint-disable-next-line no-console
        console.log(`  - ${v.id} [${v.impact ?? "unknown"}] x${v.nodes}`);
      }
    }

    // Soft gate — keep CI green while surfacing regressions.
    expect(summary.violationsCount).toBeLessThanOrEqual(5);
  });
}
